version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ivxv-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ivxvdb
    ports:
      - "5432:5432"
    volumes:
      - ivxv-pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ivxv-app
    depends_on:
      - db
    ports:
     - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ivxvdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_LIQUIBASE_CHANGELOG: classpath:/db/changelog-master.yaml
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    # If you want to pick up code changes without rebuilding the image:
    # volumes:
    #   - ./:/workspace
    # command: ./gradlew bootRun

volumes:
  ivxv-pgdata:
