--liquibase formatted sql

--changeset you:005-create-vote-table
CREATE TABLE VOTE (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    person_id BIGINT,
    party_id BIGINT,
    generated_number BIGINT,
    creation_time TIMESTAMP,
    ciphertext VARCHAR(256)
);
