--liquibase formatted sql

--changeset you:005-create-vote-table
CREATE TABLE VOTE (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    candidate_id BIGINT,
    generated_number BIGINT,
    creation_time TIMESTAMP,
    ciphertext TEXT,
    simulated BOOLEAN
);

CREATE INDEX idx_ciphertesxt ON VOTE(ciphertext);